# This is a basic workflow to help you get started with Actions

name: update_hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # TODO Later, change to only running on main branch 
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_hub_content:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          cd .github/scripts
          pip3 install --upgrade --no-cache-dir -r requirements.txt

      - name: Set up git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
        shell: bash

      - name: Update theme download counts
        run: |
          cd .github/scripts
          python3 ./update-releases.py --update-download-counts
          git commit -m "Update theme download counts" -a  || echo "nothing to commit"

      - name: Add new plugins, themes and authors
        run: |
          cd .github/scripts
          python3 ./update-releases.py --all
          cd ../..
          git add .
          git commit -m "Add new plugins, themes and authors" -a  || echo "nothing to commit"

      - name: Update MOC files
        run: |
          cd .github/scripts
          python3 ./update-mocs.py
          cd ../..
          git add .
          git commit -m "Update MOC files" -a  || echo "nothing to commit"

      # Reference: https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Scripted update of Hub content
          labels: |
            scripted update

      - name: Show Pull Request
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"